# Generated by Django 5.2.8 on 2025-11-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dependencies',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(related_name='dependents_tasks', through='core.Dependencies', to='core.tasks')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='dependencies',
            name='from_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_tasks', to='core.tasks'),
        ),
        migrations.AddField(
            model_name='dependencies',
            name='to_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_tasks', to='core.tasks'),
        ),
        migrations.AlterUniqueTogether(
            name='dependencies',
            unique_together={('from_task', 'to_task')},
        ),
    ]
