# Generated by Django 5.2.8 on 2025-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dependencies',
            field=models.ManyToManyField(related_name='dependents', through='core.Dependencies', to='core.tasks'),
        ),
        migrations.AddConstraint(
            model_name='dependencies',
            constraint=models.CheckConstraint(condition=models.Q(('from_task', models.F('to_task')), _negated=True), name='prevent_self_dependency'),
        ),
    ]
