# Generated by Django 5.2.8 on 2025-12-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tasks_dependencies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencies',
            options={'verbose_name': 'Dependency', 'verbose_name_plural': 'Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
